#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
    path: /index
    controller: App\Controller\CartController::index

new:
    path: /new
    controller: App\Controller\CartController::new